/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import jade.core.Profile;
import jade.core.ProfileImpl;
import jade.wrapper.AgentController;
import jade.wrapper.ContainerController;
import jade.wrapper.StaleProxyException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Torre
 */
public class PantallaInicial extends javax.swing.JFrame {
    private VentanaTurista ventanaTurista;
    private VentanaAgencia ventanaAgencia;
    private VentanaLugar ventanaLugar;
    private VentanaTransporte ventanaTransporte;
    private final ContainerController mainContainer;
    private AgentController ac;
    private final jade.core.Runtime rt;
    private int turista=0;
    private AgentController rma;
    /**
     * Creates new form PantallaInicial
     */
    public PantallaInicial() {
        initComponents();
        rt = jade.core.Runtime.instance(); 
        Profile p = new ProfileImpl();
        mainContainer = rt.createMainContainer(p);
        cargarEscenario();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearTurista = new javax.swing.JButton();
        crearAgencia = new javax.swing.JButton();
        crearLugar = new javax.swing.JButton();
        crearTransporte = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreServicio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cerrar = new javax.swing.JButton();
        verCargados = new javax.swing.JButton();
        abrirJade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        crearTurista.setText("Comprar Paquete Turístico");
        crearTurista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTuristaActionPerformed(evt);
            }
        });

        crearAgencia.setText("Agencia de Viajes");
        crearAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAgenciaActionPerformed(evt);
            }
        });

        crearLugar.setText(" Alojamiento");
        crearLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLugarActionPerformed(evt);
            }
        });

        crearTransporte.setText(" Empresa de Transporte");
        crearTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTransporteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Crear un nuevo servicio");

        nombreServicio.setText("Nombre del servicio");
        nombreServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreServicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese el nombre del servicio, y luego seleccione el tipo");

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        verCargados.setText("Ver servicios cargados");

        abrirJade.setText("Abrir plataforma JADE");
        abrirJade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirJadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cerrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(crearAgencia)
                                        .addGap(6, 6, 6)
                                        .addComponent(crearLugar)))
                                .addGap(10, 10, 10)
                                .addComponent(crearTransporte))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(crearTurista))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(verCargados, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(abrirJade)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(crearTurista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verCargados)
                    .addComponent(abrirJade))
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(nombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearAgencia)
                    .addComponent(crearLugar)
                    .addComponent(crearTransporte))
                .addGap(30, 30, 30)
                .addComponent(cerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearTuristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTuristaActionPerformed
        // TODO add your handling code here:
        try {
           ac= mainContainer.createNewAgent("Turista"+turista, "Agents.AgenteTurista", null);
           ac.start();
        } catch (StaleProxyException ex) {
	   JOptionPane.showMessageDialog(this, "Debe elegir otro nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }
        turista= turista+1;
                
    }//GEN-LAST:event_crearTuristaActionPerformed

    private void crearAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAgenciaActionPerformed
        // TODO add your handling code here:
      if("".equals(nombreServicio.getText())){
        JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
      }else{  
        try {
           ac= mainContainer.createNewAgent(nombreServicio.getText(), "Agents.AgenteAgenciaTurismo", null);
           ac.start();
        } catch (StaleProxyException ex) {
	   JOptionPane.showMessageDialog(this, "Debe elegir otro nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }
      }  
    }//GEN-LAST:event_crearAgenciaActionPerformed

    private void crearLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLugarActionPerformed
        // TODO add your handling code here:
      if("".equals(nombreServicio.getText())){
        JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
      }else{
        try {
           ac= mainContainer.createNewAgent(nombreServicio.getText(), "Agents.AgenteLugar", null);
           ac.start();
        } catch (StaleProxyException ex) {
	   JOptionPane.showMessageDialog(this, "Debe elegir otro nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }
      }

    }//GEN-LAST:event_crearLugarActionPerformed

    private void crearTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTransporteActionPerformed
        // TODO add your handling code here:
      if("".equals(nombreServicio.getText())){
        JOptionPane.showMessageDialog(this, "Debe ingresar un nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
      }else{
        try {
           ac= mainContainer.createNewAgent(nombreServicio.getText(), "Agents.AgenteTransporte", null);
           ac.start();
        } catch (StaleProxyException ex) {
	   JOptionPane.showMessageDialog(this, "Debe elegir otro nombre de servicio", "Error", JOptionPane.ERROR_MESSAGE);
        }
      }  
    }//GEN-LAST:event_crearTransporteActionPerformed

    private void nombreServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreServicioActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        rt.shutDown();
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed

    private void abrirJadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirJadeActionPerformed
        // TODO add your handling code here:
        try {
           rma= mainContainer.createNewAgent("rma", "jade.tools.rma.rma", null);
           rma.start();
        } catch (StaleProxyException ex) {
	   JOptionPane.showMessageDialog(this, "No se puede cargar el RMA", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_abrirJadeActionPerformed
    
    private void cargarEscenario() {
        AgentController v1;
        AgentController v2;
        AgentController v3;
        AgentController aLugar1 = null;
        AgentController aLugar2 = null;
        AgentController aLugar3 = null;
        AgentController aLugar4 = null;
        AgentController aLugar5 = null;
        AgentController aLugar6 = null;
        AgentController aTransporte1 = null;
        AgentController aTransporte2 = null;
        AgentController aTransporte3 = null;
        AgentController aTransporte4 = null;
        AgentController aTransporte5 = null;
        AgentController aTransporte6 = null;
        
        //crear arreglos para hacer mas facil la creación
        AgentController[] lugares = new  AgentController[6];
        AgentController [] transportes = new  AgentController[6];
        //cargar arreglos
        lugares[0]=aLugar1; lugares[1]=aLugar2; lugares[2]=aLugar3; lugares[3]=aLugar4; lugares[4]=aLugar5; lugares[5]=aLugar6;
        transportes[0]=aTransporte1; transportes[1]=aTransporte2; transportes[2]=aTransporte3; 
        transportes[3]=aTransporte4; transportes[4]=aTransporte5; transportes[5]=aTransporte6; 
        
        /*Se crean dos casos de Lugar y Transporte
        
        CASO 1 
        Se crean 4 lugares y 4 transportes con Buenos Aires como ciudad o destino según corresponda
        CASO 2
        Se crean 2 lugares y 2 transportes con Posadas como ciudad o destino según corresponda
        
        En cualquier caso el origen es siempre Corrientes
        Los demás atributos correspondientes dependen del número u orden y serán tratados en el Agente correspondiente
        
        */
        
        // argumentos para las agencias que cargan diferentes descuentos estará ordenado [dtoPropio, dtoLugares, dtoTransporteS]
        
        String[] argsAg = new String [3];
        
        //argumentos para los lugares y transportes, tendrá una ciudad  y un número que indica con qué se carga en la clase Agente correspondiente
        String[] argsS = {"Buenos Aires","1","Buenos Aires","2","Buenos Aires","3","Buenos Aires","4"};
        String[] argsS2 = {"Posadas","1","Posadas","2"};
        
        
        
            //Caso1 BsAs
        int c = 1;
        for(int i=0; i<=6; i= i+2){
        try {
            aLugar1 = mainContainer.createNewAgent("Lugar"+(i+c), "Agents.AgenteLugar", Arrays.copyOfRange(argsS, i, i+2));
            aLugar1.start();
            aTransporte1= mainContainer.createNewAgent("Transporte"+(i+c), "Agents.AgenteTransporte", Arrays.copyOfRange(argsS, i, i+2));
            aTransporte1.start();
            c= c-1;
        } catch (StaleProxyException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        int d=5;
        for(int i=0; i<=2; i= i+2){
        try {
            aLugar2 = mainContainer.createNewAgent("Lugar"+(i+d), "Agents.AgenteLugar", Arrays.copyOfRange(argsS2, i, i+2));
            aLugar2.start();
            aTransporte2= mainContainer.createNewAgent("Transporte"+(i+d), "Agents.AgenteTransporte", Arrays.copyOfRange(argsS2, i, i+2));
            aTransporte2.start();
            c=-1;
        } catch (StaleProxyException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
           
        //CREACIÓN DE AGENCIAS: los descuentos fueron elegidos al azar
        try {
            argsAg[0]= "42" ; argsAg[1]= "9" ; argsAg[2]= "36";
            v1= mainContainer.createNewAgent("Agencia1", "Agents.AgenteAgenciaTurismo", argsAg);
            v1.start();
            argsAg[0]= "51" ; argsAg[1]= "32" ; argsAg[2]= "10";
            v2= mainContainer.createNewAgent("Agencia2", "Agents.AgenteAgenciaTurismo", argsAg);
            v2.start();
            argsAg[0]= "25" ; argsAg[1]= "37" ; argsAg[2]= "21";
            v3= mainContainer.createNewAgent("Agencia3", "Agents.AgenteAgenciaTurismo", argsAg);
            v3.start();
            
        } catch (StaleProxyException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equalsIgnoreCase(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicial().setVisible(true);
            }
        });
    }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirJade;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton crearAgencia;
    private javax.swing.JButton crearLugar;
    private javax.swing.JButton crearTransporte;
    private javax.swing.JButton crearTurista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreServicio;
    private javax.swing.JButton verCargados;
    // End of variables declaration//GEN-END:variables

    

    
    
}
