/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Agents.AgenteLugar;
import Agents.AgenteLugar.Tipo;
import jade.core.AID;
import jade.domain.DFService;
import jade.domain.FIPAAgentManagement.DFAgentDescription;
import jade.domain.FIPAAgentManagement.ServiceDescription;
import jade.domain.FIPAException;
import jade.lang.acl.ACLMessage;
import jade.util.Logger;
import java.util.*;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author Torre
 */
public class VentanaLugar extends javax.swing.JFrame {
    
    private AgenteLugar miAgente;
    private String[] tiposLugar = {"HOTEL", "APART", "CABAÑA", "HOSTAL"};
    private ArrayList<String> servicios = new ArrayList<>();
    
    /**
     * Creates new form ventanaLugarPeor
     */
    public VentanaLugar(AgenteLugar a) {
        super(a.getLocalName());
	miAgente = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        calidad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calefaccion = new javax.swing.JCheckBox();
        pension = new javax.swing.JCheckBox();
        garage = new javax.swing.JCheckBox();
        juegos = new javax.swing.JCheckBox();
        descuentosAplicables = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        piscina = new javax.swing.JCheckBox();
        sauna = new javax.swing.JCheckBox();
        cable = new javax.swing.JCheckBox();
        internet = new javax.swing.JCheckBox();
        limpieza = new javax.swing.JCheckBox();
        cuarto = new javax.swing.JCheckBox();
        gimnasio = new javax.swing.JCheckBox();
        mascotas = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        selAgencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Alojamiento " + miAgente.getLocalName());

        jLabel2.setText("Tipo");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(tiposLugar));
        tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoItemStateChanged(evt);
            }
        });
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Calidad");

        calidad.setEnabled(false);

        jLabel4.setText("Ciudad");

        ciudad.setText(" ");
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        jLabel5.setText("Servicios Disponibles:");

        calefaccion.setText("AA/CC - Calefacción");

        pension.setText("Media Pensión");
        pension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensionActionPerformed(evt);
            }
        });

        garage.setText("Garage");
        garage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garageActionPerformed(evt);
            }
        });

        juegos.setText("Salón de Juegos");

        descuentosAplicables.setText("Definir descuentos aplicables");
        descuentosAplicables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentosAplicablesActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        piscina.setText("Piscina");

        sauna.setText("Sauna");

        cable.setText("TV con Cable");
        cable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cableActionPerformed(evt);
            }
        });

        internet.setText("Internet WiFi");

        limpieza.setText("Servicio de Limpieza");

        cuarto.setText("Servicio al Cuarto");

        gimnasio.setText("Gimnasio");

        mascotas.setText("Admiten Mascotas");

        jLabel6.setText("Precio por persona");

        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
        });

        selAgencias.setText("Agregar Agencias");
        selAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selAgenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descuentosAplicables)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pension)
                                            .addComponent(calefaccion)
                                            .addComponent(garage)
                                            .addComponent(juegos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sauna)
                                            .addComponent(piscina)
                                            .addComponent(cable)
                                            .addComponent(internet)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuarto)
                                    .addComponent(limpieza)
                                    .addComponent(gimnasio)
                                    .addComponent(mascotas)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(aceptar)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selAgencias)
                            .addComponent(cancelar))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calefaccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pension)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(garage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(juegos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piscina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sauna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(internet))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpieza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuarto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gimnasio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mascotas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descuentosAplicables)
                    .addComponent(selAgencias))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ciudadActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void descuentosAplicablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentosAplicablesActionPerformed
        // TODO add your handling code here:
        VentanaLugar.DescuentosAplicables descuentos = this.new DescuentosAplicables();
        descuentos.setVisible(true);
        setEnabled(false);
    }//GEN-LAST:event_descuentosAplicablesActionPerformed

    private void garageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garageActionPerformed

    private void cableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cableActionPerformed

    private void pensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pensionActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
      if(precio.getText() != null && ciudad.getText() != null){
        int precioPersona= Integer.parseInt(precio.getText());
        int cal= Integer.parseInt((String) calidad.getSelectedItem());
        miAgente.asignarServicios(definirServicios());
        miAgente.definirLugar(ciudad.getText(),precioPersona, cal,definirTipo(tipo.getSelectedItem()));
        this.dispose();
      } else { JOptionPane.showMessageDialog(this, "Error: Todos los campos deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);}  
    }//GEN-LAST:event_aceptarActionPerformed

    private void tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoItemStateChanged
        // TODO add your handling code here:
        if(tipo.getSelectedIndex()<2){
            calidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5"}));
        } else { calidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3"}));;
        }
        
        calidad.setEnabled(true);
        
    }//GEN-LAST:event_tipoItemStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        miAgente.doDelete();
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void selAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selAgenciasActionPerformed
        // TODO add your handling code here:
        VentanaLugar.DFAgencias guiAgencia = this.new DFAgencias();
        guiAgencia.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_selAgenciasActionPerformed

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_precioKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox cable;
    private javax.swing.JCheckBox calefaccion;
    private javax.swing.JComboBox calidad;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JCheckBox cuarto;
    private javax.swing.JButton descuentosAplicables;
    private javax.swing.JCheckBox garage;
    private javax.swing.JCheckBox gimnasio;
    private javax.swing.JCheckBox internet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JCheckBox juegos;
    private javax.swing.JCheckBox limpieza;
    private javax.swing.JCheckBox mascotas;
    private javax.swing.JCheckBox pension;
    private javax.swing.JCheckBox piscina;
    private javax.swing.JTextField precio;
    private javax.swing.JCheckBox sauna;
    private javax.swing.JButton selAgencias;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables

    private Tipo definirTipo(Object a) {
        String b = (String) a;
        Tipo tipoD = null;
        switch(b){
            case "HOTEL":
                tipoD= Tipo.HOTEL;
                break;
            case "APART":
                tipoD= Tipo.APART;
                break;
            case "HOSTAL":
                tipoD= Tipo.HOSTAL;
                break;
            case "CABAÑA":
                tipoD= Tipo.CABAÑA;
                break;
        }
        return tipoD;
    }

    private String[] definirServicios() {
        if (calefaccion.isSelected())
            servicios.add(calefaccion.getText());
        if(pension.isSelected())
            servicios.add(pension.getText());
        if(garage.isSelected())
            servicios.add(garage.getText());
        if(juegos.isSelected())
            servicios.add(juegos.getText());
        if(piscina.isSelected())
            servicios.add(piscina.getText());
        if(sauna.isSelected())
            servicios.add(sauna.getText());
        if(cable.isSelected())
            servicios.add(cable.getText());
        if(internet.isSelected())
            servicios.add(internet.getText());
        if(limpieza.isSelected())
            servicios.add(limpieza.getText());
        if(cuarto.isSelected())
            servicios.add(cuarto.getText());
        if(gimnasio.isSelected())
            servicios.add(gimnasio.getText());
        if(mascotas.isSelected())
            servicios.add(mascotas.getText());
        String[] services = new String[servicios.size()];
        services = servicios.toArray(services);
        return services;
    }
    public class DescuentosAplicables extends javax.swing.JFrame {

    /**
     * Creates new form DescuentosAsignados
     */
    private float [] personas = new float[1];
    private float [] anticipacion = new float[1];
    private float [] cantDias = new float[1];
    private float[][] descuentos;
    private AgenteLugar miAgente;
    
    
    public DescuentosAplicables() {
        initComponents();
        personas[0] = 0;
        anticipacion [0] = 0;
        cantDias [0] = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        psas1 = new javax.swing.JTextField();
        psas2 = new javax.swing.JTextField();
        psas3 = new javax.swing.JTextField();
        dtoPsas1 = new javax.swing.JTextField();
        dtoPsas2 = new javax.swing.JTextField();
        dtoPsas3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dtoDias1 = new javax.swing.JTextField();
        dtoDias2 = new javax.swing.JTextField();
        dtoDias3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dias1 = new javax.swing.JTextField();
        dias2 = new javax.swing.JTextField();
        dias3 = new javax.swing.JTextField();
        anticipacion2 = new javax.swing.JTextField();
        anticipacion3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dtoA1 = new javax.swing.JTextField();
        dtoA2 = new javax.swing.JTextField();
        dtoA3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        anticipacion1 = new javax.swing.JTextField();
        agregarPsas = new javax.swing.JButton();
        agregarDias = new javax.swing.JButton();
        agregarAnti = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Descuentos Asignables");

        jLabel2.setText("Según cantidad de personas");

        jLabel3.setText("Cantidad Mínima");

        jLabel4.setText("Descuento (%)");

        psas1.setText("0");
        psas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psas1ActionPerformed(evt);
            }
        });

        psas2.setText("0");

        psas3.setText("0");

        dtoPsas1.setText("0");
        dtoPsas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoPsas1ActionPerformed(evt);
            }
        });

        dtoPsas2.setText("0");

        dtoPsas3.setText("0");

        jLabel5.setText("Según cantidad de días de hospedaje");

        dtoDias1.setText("0");
        dtoDias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoDias1ActionPerformed(evt);
            }
        });

        dtoDias2.setText("0");

        dtoDias3.setText("0");

        jLabel6.setText("Cantidad Mínima");

        jLabel7.setText("Descuento (%)");

        dias1.setText("0");
        dias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dias1ActionPerformed(evt);
            }
        });

        dias2.setText("0");

        dias3.setText("0");

        anticipacion2.setText("0");

        anticipacion3.setText("0");

        jLabel8.setText("Según cantidad de días de anticipación de reserva");

        dtoA1.setText("0");
        dtoA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtoA1ActionPerformed(evt);
            }
        });

        dtoA2.setText("0");

        dtoA3.setText("0");

        jLabel9.setText("Cantidad Mínima");

        jLabel10.setText("Descuento (%)");

        anticipacion1.setText("0");
        anticipacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anticipacion1ActionPerformed(evt);
            }
        });

        agregarPsas.setText("Agregar");
        agregarPsas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPsasActionPerformed(evt);
            }
        });

        agregarDias.setText("Agregar");
        agregarDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDiasActionPerformed(evt);
            }
        });

        agregarAnti.setText("Agregar");
        agregarAnti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAntiActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(anticipacion1)
                                                .addComponent(anticipacion2)
                                                .addComponent(anticipacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel10))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dtoA1)
                                                .addComponent(dtoA2)
                                                .addComponent(dtoA3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(agregarAnti))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dias1)
                                                .addComponent(dias2)
                                                .addComponent(dias3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel7))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dtoDias1)
                                                .addComponent(dtoDias2)
                                                .addComponent(dtoDias3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(psas1)
                                                .addComponent(psas2)
                                                .addComponent(psas3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel4))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(dtoPsas1)
                                                .addComponent(dtoPsas2)
                                                .addComponent(dtoPsas3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(64, 64, 64)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(agregarDias)
                                                .addComponent(agregarPsas))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(aceptar)
                .addGap(54, 54, 54)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(psas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(psas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtoPsas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtoPsas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtoPsas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(agregarPsas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtoDias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtoDias2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtoDias3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarDias))))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anticipacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anticipacion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anticipacion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dtoA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtoA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dtoA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarAnti))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap())
        );
        
                anticipacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anticipacion1KeyTyped(evt);
                }
        });
        
        anticipacion2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anticipacion2KeyTyped(evt);
                }
        });
        
        anticipacion3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anticipacion3KeyTyped(evt);
                }
        });
        
        dtoA1.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                dtoA1KeyTyped(evt);
            }
        });
        
        dtoA2.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                dtoA2KeyTyped(evt);
            }
        });
        
        dtoA3.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                dtoA3KeyTyped(evt);
            }
        });
        
        dtoPsas1.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoPsas1KeyTyped(evt);
             }
        });
        
        dtoPsas2.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoPsas2KeyTyped(evt);
             }
        });
        
        dtoPsas3.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoPsas3KeyTyped(evt);
             }
        });
        
        psas1.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 psas1KeyTyped(evt);
             }
        });
        
        psas2.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 psas2KeyTyped(evt);
             }
        });
        
        psas3.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 psas3KeyTyped(evt);
             }
        });
        
        dias1.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dias1KeyTyped(evt);
             }
        });
        
        dias2.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dias2KeyTyped(evt);
             }
        });
        
        dias3.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dias3KeyTyped(evt);
             }
        });
        
        dtoDias1.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoDias1KeyTyped(evt);
             }
        });
        
        dtoDias2.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoDias2KeyTyped(evt);
             }
        });
        
        dtoDias3.addKeyListener(new java.awt.event.KeyAdapter() {
             public void keyTyped(java.awt.event.KeyEvent evt) {
                 dtoDias3KeyTyped(evt);
             }
        });

        pack();
    }// </editor-fold>                        

    private void psas1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void dtoPsas1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void dtoDias1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void dias1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void dtoA1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void anticipacion1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void agregarDiasActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
     if(dias1.getText()!=null && dias2.getText()!=null && dias3.getText()!=null &&
           dtoDias1.getText()!=null && dtoDias2.getText()!=null && dtoDias3.getText()!=null ){  
       if(Integer.parseInt(dtoDias1.getText())<=100 && Integer.parseInt(dtoDias2.getText())<=100 && Integer.parseInt(dtoDias3.getText())<=100){ 
         int uno = Integer.parseInt(dias1.getText());
         int dos = Integer.parseInt(dias2.getText());
         int tres = Integer.parseInt(dias3.getText());
         int max = Integer.max(Integer.max(uno, dos), tres);
         if(max>cantDias.length)
            cantDias = Arrays.copyOf(cantDias, max+1);
        
         cantDias[uno] = Float.parseFloat(dtoDias1.getText())/100;
         cantDias[dos] = Float.parseFloat(dtoDias2.getText())/100;
         cantDias[tres] = Float.parseFloat(dtoDias3.getText())/100;
        
         limpiarDias();
       } else { JOptionPane.showMessageDialog(this, "Error: Descuento no puede ser mayor a 100", "Error", JOptionPane.ERROR_MESSAGE);}
     } else {JOptionPane.showMessageDialog(this, "Error: Todos los campos deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);}
     
    }                                           

    private void agregarPsasActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
      if(psas1.getText()!=null && psas2.getText()!=null && psas3.getText()!=null &&
           dtoPsas1.getText()!=null && dtoPsas2.getText()!=null && dtoPsas3.getText()!=null ){  
        if(Integer.parseInt(dtoPsas1.getText())<=100 && Integer.parseInt(dtoPsas2.getText())<=100 && Integer.parseInt(dtoPsas3.getText())<=100){ 
            int uno = Integer.parseInt(psas1.getText());
            int dos = Integer.parseInt(psas2.getText());
            int tres = Integer.parseInt(psas3.getText());
            int max = Integer.max(Integer.max(uno, dos), tres);
            if(personas.length<=max)
                personas = Arrays.copyOf(personas, max+1);
        
            personas[uno] = Float.parseFloat(dtoPsas1.getText())/100;
            personas[dos] = Float.parseFloat(dtoPsas2.getText())/100;
            personas[tres] = Float.parseFloat(dtoPsas3.getText())/100;
        
            limpiarPersonas();
      } else { JOptionPane.showMessageDialog(this, "Error: Descuento no puede ser mayor a 100", "Error", JOptionPane.ERROR_MESSAGE);}
     } else {JOptionPane.showMessageDialog(this, "Error: Todos los campos deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);}
       
    }                                           

    private void agregarAntiActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
     if(anticipacion1.getText()!= null && anticipacion2.getText()!= null && anticipacion3.getText()!= null 
                && dtoA1.getText()!= null && dtoA2.getText()!= null && dtoA3.getText()!= null){
         
       if(Integer.parseInt(dtoA1.getText())<=100 && Integer.parseInt(dtoA2.getText())<=100 && Integer.parseInt(dtoA3.getText())<=100){
         int uno = Integer.parseInt(anticipacion1.getText());
         int dos = Integer.parseInt(anticipacion2.getText());
         int tres = Integer.parseInt(anticipacion3.getText());
         int max = Integer.max(Integer.max(uno, dos), tres);
         if(anticipacion.length<=max)
            anticipacion = Arrays.copyOf(anticipacion, max+1);
        
         anticipacion[uno] = Float.parseFloat(dtoA1.getText())/100;
         anticipacion[dos] = Float.parseFloat(dtoA2.getText())/100;
         anticipacion[tres] = Float.parseFloat(dtoA3.getText())/100;
        
         limpiarAnticipacion();
       } else { JOptionPane.showMessageDialog(this, "Error: Descuento no puede ser mayor a 100", "Error", JOptionPane.ERROR_MESSAGE);}
     } else {JOptionPane.showMessageDialog(this, "Error: Todos los campos deben estar completos", "Error", JOptionPane.ERROR_MESSAGE);}
     
    }
    
    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        VentanaLugar.this.setEnabled(true);
        this.dispose();
    } 

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        agregarDiasActionPerformed(null);
        agregarPsasActionPerformed(null);
        agregarAntiActionPerformed(null);
        for(int i = 1; i<personas.length; ++i){
            if(personas[i] == 0)
                personas[i] = personas[i-1];
        }
        for(int i =1; i<anticipacion.length; ++i){
            if(anticipacion[i] == 0)
                anticipacion[i] = anticipacion[i-1];
        }
        for(int i = 1; i< cantDias.length; ++i){
            if(cantDias[i] == 0)
                cantDias[i] = cantDias[i-1];
        }
        
        VentanaLugar.this.miAgente.asignarDescuentoPersonas(personas);
        VentanaLugar.this.miAgente.asignarDescuentoDias(cantDias);
        VentanaLugar.this.miAgente.asignarDescuentoAnticipación(anticipacion);
        VentanaLugar.this.setEnabled(true);
        dispose();
    }  
    
    private void anticipacion1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void anticipacion2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void anticipacion3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoA1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoA2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoA3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoPsas1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoPsas2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoPsas3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void psas1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void psas2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void psas3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dias1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dias2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dias3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoDias1KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoDias2KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    
    private void dtoDias3KeyTyped(java.awt.event.KeyEvent evt) {                                     
        
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton aceptar;
    private javax.swing.JButton agregarAnti;
    private javax.swing.JButton agregarDias;
    private javax.swing.JButton agregarPsas;
    private javax.swing.JTextField anticipacion1;
    private javax.swing.JTextField anticipacion2;
    private javax.swing.JTextField anticipacion3;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField dias1;
    private javax.swing.JTextField dias2;
    private javax.swing.JTextField dias3;
    private javax.swing.JTextField dtoA1;
    private javax.swing.JTextField dtoA2;
    private javax.swing.JTextField dtoA3;
    private javax.swing.JTextField dtoDias1;
    private javax.swing.JTextField dtoDias2;
    private javax.swing.JTextField dtoDias3;
    private javax.swing.JTextField dtoPsas1;
    private javax.swing.JTextField dtoPsas2;
    private javax.swing.JTextField dtoPsas3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField psas1;
    private javax.swing.JTextField psas2;
    private javax.swing.JTextField psas3;
    // End of variables declaration                   

    private void limpiarPersonas() {
        psas1.setText("0");
        psas2.setText("0");
        psas3.setText("0");
        dtoPsas1.setText("0");
        dtoPsas2.setText("0");
        dtoPsas3.setText("0");
        
    }

    private void limpiarDias() {
        dias1.setText("0");
        dias2.setText("0");
        dias3.setText("0");
        dtoDias1.setText("0");
        dtoDias2.setText("0");
        dtoDias3.setText("0");
       
    }

    private void limpiarAnticipacion() {
        anticipacion1.setText("0");
        anticipacion2.setText("0");
        anticipacion3.setText("0");
        dtoA1.setText("0");
        dtoA2.setText("0");
        dtoA3.setText("0");
        
                
    }
}
    
    // Asignar Agencias
    
    public class DFAgencias extends javax.swing.JFrame {
    
    private String [] agencias;
    DFAgentDescription [] resultados;

    /**
     * Creates new form DFAgencias
     */
    public DFAgencias() {
        getAgencias();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaAgencias = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar Agencias Asociadas");

        jLabel2.setText("Agencias Disponibles");

        listaAgencias.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return agencias.length; }
            public Object getElementAt(int i) { return agencias[i]; }
        });
        jScrollPane1.setViewportView(listaAgencias);

        jLabel3.setText("Para seleccionar mas de una agencia mantenga presionada la tecla Ctrl");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        VentanaLugar.this.setEnabled(true);
        dispose();
    }                                        

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        int[] seleccion = listaAgencias.getSelectedIndices();
        AID[] agenciasAID = new AID[seleccion.length];
        for(int index: seleccion){
            agenciasAID[index]=resultados[seleccion[index]].getName();
        }
        ACLMessage suscribir = new ACLMessage(ACLMessage.SUBSCRIBE);
        for(AID ag: agenciasAID){
            suscribir.addReceiver(ag);
        }
        suscribir.setContent("Lugar");
        VentanaLugar.this.miAgente.send(suscribir);
        VentanaLugar.this.setEnabled(true);
        dispose();
    }                                       


    // Variables declaration - do not modify                     
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaAgencias;
    // End of variables declaration                   

    private void getAgencias() {
       ServiceDescription servicio = new ServiceDescription();
       servicio.setType("Agencia de Turismo");
       DFAgentDescription descripcion = new DFAgentDescription();
       descripcion.addServices(servicio);
       try {
           resultados = DFService.search(VentanaLugar.this.miAgente, descripcion);
           agencias = new String [resultados.length];
           for (int i=0; i < resultados.length; ++i)
           {
               agencias [i] = resultados[i].getName().getLocalName();
           }
       } catch (FIPAException ex) {
            Logger.getLogger(DFAgencias.class.getName()).log(Level.SEVERE, null, ex);
        }
               
    }
    
}

    
}
