/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Agents.AgenteTransporte;
import Things.CronogramaTransporte;

/**
 *
 * @author Torre
 */
public class VentanaMostrarTransporte extends javax.swing.JFrame {
    
    AgenteTransporte miAgente;
    CronogramaTransporte ruta;

    /**
     * Creates new form VentanaMostrarTransporte
     * @param a
     */
    public VentanaMostrarTransporte(AgenteTransporte a) {
        super(a.getLocalName());
	miAgente = a;
        ruta= miAgente.getRutas().get(0);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        tipoEmp = new javax.swing.JLabel();
        comodidad = new javax.swing.JLabel();
        origen = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dtoAnti = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        dtoPsas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dtoDias = new javax.swing.JTable();
        cerrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transporte");

        titulo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Transporte: "+miAgente.getLocalName());

        tipoEmp.setText("Tipo de Empresa: "+miAgente.getTipoString());

        comodidad.setText("Comodidad: "+ruta.getCalidadString());

        origen.setText("Origen: "+ruta.getOrigen());

        destino.setText("Destino: "+ruta.getDestino());

        precio.setText("Precio por Persona: $"+ruta.getPrecioPersona());

        jLabel1.setText("Salidas: "+ruta.getSalidas().toString());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Descuentos según Anticipación");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Descuento según Cantidad de Personas");

        dtoAnti.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dtoAnti.setModel(new javax.swing.table.DefaultTableModel(
            obtenerListaDescuentos(miAgente.getDescuentoPorAnticipacion())
            ,
            new String [] {
                "Cantidad de Días", "Descuento(%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(dtoAnti);
        if (dtoAnti.getColumnModel().getColumnCount() > 0) {
            dtoAnti.getColumnModel().getColumn(0).setResizable(false);
            dtoAnti.getColumnModel().getColumn(1).setResizable(false);
        }

        dtoPsas.setModel(new javax.swing.table.DefaultTableModel(
            obtenerListaDescuentos(miAgente.getDescuentoPorPersonas())
            ,
            new String [] {
                "Cantidad de Personas", "Descuento(%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(dtoPsas);
        if (dtoPsas.getColumnModel().getColumnCount() > 0) {
            dtoPsas.getColumnModel().getColumn(0).setResizable(false);
            dtoPsas.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Descuentos según Días");

        dtoDias.setModel(new javax.swing.table.DefaultTableModel(
            obtenerListaDias(miAgente.getDescuentoPorDias())
            ,
            new String [] {
                "Día de la Semana", "Descuento(%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(dtoDias);
        if (dtoDias.getColumnModel().getColumnCount() > 0) {
            dtoDias.getColumnModel().getColumn(0).setResizable(false);
            dtoDias.getColumnModel().getColumn(1).setResizable(false);
        }

        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(cerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(origen)
                                .addGap(18, 18, 18)
                                .addComponent(destino))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tipoEmp)
                                .addGap(18, 18, 18)
                                .addComponent(comodidad))
                            .addComponent(precio)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(112, 112, 112))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cerrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origen)
                            .addComponent(destino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipoEmp)
                            .addComponent(comodidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarActionPerformed
    
    private Object[][] obtenerListaDescuentos(float[] descuentos) {
        float dtoMax = -1;
        int contador = 0;
        int[] indices= new int[descuentos.length];
        float[] valores= new float[descuentos.length];
        Object[][] listaDesc;
        
        for(int i=0; i<descuentos.length; i++){
            if(dtoMax!=descuentos[i]){
                valores[contador]= descuentos[i]*100;
                indices[contador]= i;
                dtoMax= descuentos[i];
                contador++;
            }
        }
        if(contador>1){
            listaDesc = new Object[contador-1][2];
            for (int j=0; j<listaDesc.length; j++){
                listaDesc[j][0]= indices[j+1];
                listaDesc[j][1]= valores[j+1];
            }
        }else{
            listaDesc = new Object[contador][2];
            listaDesc[0][0]= null;
            listaDesc[0][1]= null;
        }
        
        
        
        return listaDesc;
    }
    
    private Object[][] obtenerListaDias(float[] descuentos){
        Object[][] lista = new Object[7][2];
        for(int i =0; i<descuentos.length; i++){
            lista[i][1]=descuentos[i]*100;
        }
        lista[0][0]="Lunes";
        lista[1][0]="Martes";
        lista[2][0]="Miércoles";
        lista[3][0]="Jueves";
        lista[4][0]="Viernes";
        lista[5][0]="Sábado";
        lista[6][0]="Domingo";
        return lista;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel comodidad;
    private javax.swing.JLabel destino;
    private javax.swing.JTable dtoAnti;
    private javax.swing.JTable dtoDias;
    private javax.swing.JTable dtoPsas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel origen;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel tipoEmp;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
