/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ventanas;

import Agents.AgenteLugar;
import javax.swing.Popup;

/**
 *
 * @author Torre
 */
public class VentanaLugar extends javax.swing.JFrame {
    
    private AgenteLugar miAgente;
    private String[] tiposLugar = {"HOTEL", "APART", "CABAÑA", "HOSTAL"};
    
    
    /**
     * Creates new form ventanaLugarPeor
     */
    public VentanaLugar(AgenteLugar a) {
        super(a.getLocalName());
	miAgente = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        calidad = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ciudad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calefaccion = new javax.swing.JCheckBox();
        pension = new javax.swing.JCheckBox();
        garage = new javax.swing.JCheckBox();
        juegos = new javax.swing.JCheckBox();
        descuentosAplicables = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        piscina = new javax.swing.JCheckBox();
        sauna = new javax.swing.JCheckBox();
        cable = new javax.swing.JCheckBox();
        internet = new javax.swing.JCheckBox();
        limpieza = new javax.swing.JCheckBox();
        cuarto = new javax.swing.JCheckBox();
        gimnasio = new javax.swing.JCheckBox();
        mascotas = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Alojamiento " + miAgente.getLocalName());

        jLabel2.setText("Tipo");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(tiposLugar));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Calidad");

        calidad.setEnabled(false);

        jLabel4.setText("Ciudad");

        ciudad.setText(" ");
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        jLabel5.setText("Servicios Disponibles:");

        calefaccion.setText("AA/CC - Calefacción");

        pension.setText("Media Pensión");
        pension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensionActionPerformed(evt);
            }
        });

        garage.setText("Garage");
        garage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garageActionPerformed(evt);
            }
        });

        juegos.setText("Salón de Juegos");

        descuentosAplicables.setText("Definir descuentos aplicables");
        descuentosAplicables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentosAplicablesActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");

        piscina.setText("Piscina");

        sauna.setText("Sauna");

        cable.setText("TV con Cable");
        cable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cableActionPerformed(evt);
            }
        });

        internet.setText("Internet WiFi");

        limpieza.setText("Servicio de Limpieza");

        cuarto.setText("Servicio al Cuarto");

        gimnasio.setText("Gimnasio");

        mascotas.setText("Admiten Mascotas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descuentosAplicables)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pension)
                                            .addComponent(calefaccion)
                                            .addComponent(garage)
                                            .addComponent(juegos))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sauna)
                                            .addComponent(piscina)
                                            .addComponent(cable)
                                            .addComponent(internet)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cuarto)
                                    .addComponent(limpieza)
                                    .addComponent(gimnasio)
                                    .addComponent(mascotas)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(aceptar)
                        .addGap(69, 69, 69)
                        .addComponent(cancelar)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(calidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calefaccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pension)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(garage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(juegos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(piscina)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sauna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(internet))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(limpieza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuarto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gimnasio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mascotas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(descuentosAplicables)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ciudadActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
        if(tipo.getSelectedIndex()<3){
            calidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5"}));
        } else { calidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3"}));;
        }
        
        calidad.setEnabled(true);
    }//GEN-LAST:event_tipoActionPerformed

    private void descuentosAplicablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentosAplicablesActionPerformed
        // TODO add your handling code here:
        DescuentosAplicables descuentos = new DescuentosAplicables(miAgente);
        descuentos.setVisible(true);
    }//GEN-LAST:event_descuentosAplicablesActionPerformed

    private void garageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_garageActionPerformed

    private void cableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cableActionPerformed

    private void pensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pensionActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JCheckBox cable;
    private javax.swing.JCheckBox calefaccion;
    private javax.swing.JComboBox calidad;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField ciudad;
    private javax.swing.JCheckBox cuarto;
    private javax.swing.JButton descuentosAplicables;
    private javax.swing.JCheckBox garage;
    private javax.swing.JCheckBox gimnasio;
    private javax.swing.JCheckBox internet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox juegos;
    private javax.swing.JCheckBox limpieza;
    private javax.swing.JCheckBox mascotas;
    private javax.swing.JCheckBox pension;
    private javax.swing.JCheckBox piscina;
    private javax.swing.JCheckBox sauna;
    private javax.swing.JComboBox tipo;
    // End of variables declaration//GEN-END:variables

    
}
